/**
 * `<veusz-figure>` custom element — the public embed API.
 *
 * Usage on any web page:
 *   <script type="module" src=".../veusz-embed.js"></script>
 *   <veusz-figure src="myplot.vsz" width="700" height="500"></veusz-figure>
 *
 * It boots the shared in-browser Veusz runtime (Pyodide), loads the `.vsz`
 * named by `src`, and mounts the interactive figure. The heavy runtime loads
 * once and is reused by every `<veusz-figure>` on the page.
 *
 * Attributes:
 *   src           URL of the .vsz document (required)
 *   width/height  render resolution in px (the canvas scales to fit)
 *   editable      "false" to hide the edit panel
 *   poster        URL of a static image shown immediately while the runtime
 *                 boots, and kept (instead of a blank box) on browsers without
 *                 WebGPU. Generated by `veusz-embed build`.
 *   eager         "true" to load the runtime immediately. Default: when a
 *                 poster is present, defer the heavy runtime until the reader
 *                 clicks the figure (a page of figures then costs only its
 *                 posters, not N× Pyodide).
 *   wasm-base     base URL of the Vello WASM renderer (defaults to /wasm)
 *   pyodide-index Pyodide distribution dir (defaults to jsDelivr)
 *   veusz-wheel   URL of the headless veusz wheel (CDN/bundle)
 *   data-url-base base URL for resolving relative URLs the .vsz uses with
 *                 `ImportFileURL("relative.csv", …)`. Defaults to the .vsz's
 *                 own directory so co-located data files just work.
 *   data-url-map  JSON object `{"<originalURL>": "<replacementURL>"}` to
 *                 retarget specific .vsz URLs at embed time — duplicate the
 *                 element with different maps to compare data sources without
 *                 modifying the .vsz.
 *
 * WebGPU is probed *before* the heavy runtime loads: with no WebGPU we show the
 * poster (or a message) and never download Pyodide.
 */

import { createRoot, type Root } from 'react-dom/client';
import { createElement } from 'react';
import { createRpc } from '../rpc/client';
import { createDocStore } from '../state/doc';
import { webgpuAvailable } from '../components/plot/velloWasm';
import { bootVeuszRuntime } from './runtime';
import { prefetchUrlsInVsz, wireUrlLinks, type UrlLinkController } from './urlLinks';
import { fetchDataFiles } from './localData';
import { VeuszFigure } from './VeuszFigure';

const NEEDS_WEBGPU = 'This interactive figure needs WebGPU. '
  + 'Open in Chrome or Safari 26+.';

class VeuszFigureElement extends HTMLElement {
  private root: Root | null = null;
  private mounted = false;
  private noteEl: HTMLElement | null = null;
  private urlLinks: UrlLinkController | null = null;

  connectedCallback() {
    if (this.mounted) return;
    this.mounted = true;
    void this.boot();
  }

  disconnectedCallback() {
    this.urlLinks?.stop();
    this.urlLinks = null;
    this.root?.unmount();
    this.root = null;
  }

  private status(text: string) {
    this.replaceChildren();
    const d = document.createElement('div');
    d.setAttribute('data-testid', 'veusz-figure-status');
    d.style.cssText = 'font:14px system-ui;color:#555;padding:16px;'
      + 'border:1px solid #e2e4e8;border-radius:10px;';
    d.textContent = text;
    this.appendChild(d);
  }

  /** Show the static poster image. `note` adds a caption (updatable in place
   *  via {@link setNote}); `onActivate` overlays a click-to-load control. Falls
   *  back to a text status if the image fails to load (e.g. a stale URL). */
  private showPoster(url: string,
      opts: { note?: string; onActivate?: () => void } = {}) {
    this.replaceChildren();
    this.noteEl = null;
    const wrap = document.createElement('div');
    wrap.setAttribute('data-testid', 'veusz-figure-poster');
    wrap.style.cssText = 'position:relative;border:1px solid #e2e4e8;'
      + 'border-radius:10px;overflow:hidden;background:#fff;font:12px system-ui;';
    const img = document.createElement('img');
    img.src = url;
    img.alt = this.getAttribute('title') ?? 'Veusz figure';
    img.style.cssText = 'display:block;width:100%;height:auto;';
    img.addEventListener('error', () => this.status(opts.note ?? NEEDS_WEBGPU));
    wrap.appendChild(img);

    if (opts.onActivate) {
      // Discrete top-right "Edit" affordance (not a big centered overlay), so
      // the poster reads as the figure with an unobtrusive way in.
      const activate = document.createElement('button');
      activate.type = 'button';
      activate.setAttribute('data-testid', 'veusz-figure-activate');
      activate.setAttribute('aria-label', 'Edit the interactive figure');
      activate.textContent = '✎ Edit';
      activate.style.cssText = 'position:absolute;right:8px;top:8px;'
        + 'border:1px solid rgba(0,0,0,0.12);border-radius:6px;'
        + 'padding:4px 10px;cursor:pointer;font:600 12px system-ui;color:#1a1d21;'
        + 'background:rgba(255,255,255,0.92);box-shadow:0 1px 4px rgba(0,0,0,0.18);';
      activate.addEventListener('click', () => opts.onActivate!());
      wrap.appendChild(activate);
    }

    if (opts.note) {
      const cap = document.createElement('div');
      cap.setAttribute('data-testid', 'veusz-figure-poster-note');
      cap.style.cssText = 'color:#8a6d00;background:#fef7e0;padding:4px 8px;';
      cap.textContent = opts.note;
      wrap.appendChild(cap);
      this.noteEl = cap;
    }
    this.appendChild(wrap);
  }

  /** Update the poster caption in place (no image reload), for boot progress. */
  private setNote(text: string) {
    if (this.noteEl) this.noteEl.textContent = text;
  }

  private async boot() {
    const src = this.getAttribute('src');
    if (!src) { this.status('veusz-figure: missing "src"'); return; }
    const poster = this.getAttribute('poster') || undefined;

    // Probe WebGPU before the heavy boot. With no WebGPU the interactive path
    // can't run (there is no server-side fallback in the browser), so we keep
    // the static poster and never download Pyodide + the wheel + the wasm.
    if (!(await webgpuAvailable())) {
      if (poster) {
        this.showPoster(poster, {
          note: 'Static image — the interactive view needs WebGPU (Chrome or Safari 26+).',
        });
      } else {
        this.status(NEEDS_WEBGPU);
      }
      return;
    }

    // WebGPU is present. With a poster, defer the heavy runtime until the
    // reader asks for it (click), so a page of figures pays only its posters.
    // Without a poster there's nothing to show, so boot eagerly.
    const eager = this.getAttribute('eager') === 'true' || !poster;
    if (eager) {
      await this.bootInteractive(src, poster, false);
    } else {
      this.showPoster(poster!, {
        // Clicking the discrete Edit affordance boots and opens the editor.
        onActivate: () => { void this.bootInteractive(src, poster, true); },
      });
    }
  }

  /** Load the Pyodide runtime + document and mount the live figure. Keeps the
   *  poster (with progress in its caption) until the figure is ready. */
  private async bootInteractive(src: string, poster?: string, openEditor = false) {
    if (poster) this.showPoster(poster, { note: 'Loading interactive figure…' });
    else this.status('Loading…');
    try {
      const runtime = await bootVeuszRuntime({
        wasmBase: this.getAttribute('wasm-base') ?? undefined,
        pyodideIndexUrl: this.getAttribute('pyodide-index') ?? undefined,
        veuszWheelUrl: this.getAttribute('veusz-wheel') ?? undefined,
        onProgress: (s) => { if (poster) this.setNote(s); else this.status(s); },
      });

      const resp = await fetch(src);
      if (!resp.ok) throw new Error(`fetch ${src}: ${resp.status}`);
      const vszText = await resp.text();

      // URL data sources: the .vsz can `ImportFileURL(...)`. Pre-fetch every
      // URL it references and feed bytes into Pyodide via `data.url_ingest`
      // so `loadVsz` finds them synchronously. Defaults: relative URLs
      // resolve against the .vsz's own directory; `data-url-base` /
      // `data-url-map` retarget fetches without modifying document state.
      const urlOpts = {
        urlBase: this.getAttribute('data-url-base')
          ?? new URL('.', new URL(src, location.href)).toString(),
        urlMap: parseJSONAttr(this.getAttribute('data-url-map')),
      };
      await prefetchUrlsInVsz(vszText, runtime.transport, urlOpts);

      // Sidecar data: a .vsz that does `ImportFile('data.dat')` needs that file
      // present in Pyodide's FS. Fetch every referenced relative file (resolved
      // like the .vsz itself, honouring the same data-url overrides) and write
      // it alongside the document before loading.
      const dataFiles = await fetchDataFiles(vszText, src, urlOpts);

      await runtime.loadVsz(vszText, dataFiles);

      // Install per-URL polling intervals from the now-registered URL links.
      this.urlLinks = await wireUrlLinks(runtime.transport, urlOpts);

      const store = createDocStore(createRpc(runtime.transport));

      this.replaceChildren();
      this.noteEl = null;
      const container = document.createElement('div');
      this.appendChild(container);
      this.root = createRoot(container);
      // One-click reload: re-poll every URL data source via the urlLinks
      // controller (so URL bytes are refreshed and the Python side re-imports
      // them) and then ask the daemon to reload filesystem-linked data. Both
      // run regardless of whether the doc has either kind, so the button
      // works the same way in URL-only, file-only, and mixed figures.
      const onReload = async () => {
        await this.urlLinks?.refresh();
        await store.getState().reloadFile();
      };

      this.root.render(createElement(VeuszFigure, {
        store,
        width: Number(this.getAttribute('width') ?? 600),
        height: Number(this.getAttribute('height') ?? 400),
        editable: this.getAttribute('editable') !== 'false',
        title: this.getAttribute('title') ?? undefined,
        poster,
        vszUrl: src,
        initialEditing: openEditor,
        onReload,
      }));
    } catch (e) {
      const msg = (e as Error).message;
      if (poster) {
        this.showPoster(poster, {
          note: `Couldn’t load the interactive view: ${msg}. Click to retry.`,
          onActivate: () => { void this.bootInteractive(src, poster); },
        });
      } else {
        this.status(`Failed to load figure: ${msg}`);
      }
    }
  }
}

/** Parse a JSON object attribute (e.g. data-url-map). Returns undefined for
 *  null/empty input and warns + returns undefined on malformed JSON. */
function parseJSONAttr(raw: string | null): Record<string, string> | undefined {
  if (!raw) return undefined;
  try {
    const v = JSON.parse(raw);
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      return v as Record<string, string>;
    }
    console.warn('[veusz-figure] data-url-map must be a JSON object');
    return undefined;
  } catch (e) {
    console.warn('[veusz-figure] invalid data-url-map JSON:', e);
    return undefined;
  }
}

if (typeof customElements !== 'undefined'
    && !customElements.get('veusz-figure')) {
  customElements.define('veusz-figure', VeuszFigureElement);
}

export { VeuszFigureElement };
